apiVersion: v1
kind: Pod
metadata:
  name: etcd
spec:
  hostNetwork: true
  containers:
  - name: etcd
    image: {{ .Etcd.Name }}:{{ .Etcd.Tag }}
    resources:
      requests:
        cpu: 100m
    ports:
    - containerPort: 2379
      hostPort: 2379
      name: client
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 2379
      initialDelaySeconds: 5
      timeoutSeconds: 60