apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: vault
spec:
  hostNetwork: true
  containers:
  - name: vault
    image: {{ .VaultImage }}:{{ .VaultTag }}
    command:
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      timeoutSeconds: 15